<?php

namespace Database\Seeders;

use App\Models\VacationsAvailablePerUser;
use Illuminate\Database\Seeder;

class VacationUpdate extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $vacation = array(
            /// BH TRADE MARKET
            /// Periodo viejo
            (object)[
                'period' => 2,
                'days_availables' => 12.0,
                'dv' => 4,
                'days_enjoyed' => 8,
                'date_start' => '2023-07-03',
                'date_end' => '2024-07-03',
                'cutoff_date' => '2025-07-03',
                'anniversary_number' => 1,
                'users_id' => 199,
            ],
            /// Periodo nuevo
            (object)[
                'period' => 1,
                'days_availables' => 3.25,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-03',
                'date_end' => '2025-07-03',
                'cutoff_date' => '2026-07-03',
                'anniversary_number' => 2,
                'users_id' => 199,
            ],
            /// Periodo viejo
            /// Angeles tengo una duda
            (object)[
                'period' => 1,
                'days_availables' => 7.64,
                'dv' => 7,
                'days_enjoyed' => 1,
                'date_start' => '2024-02-06',
                'date_end' => '2025-02-06',
                'cutoff_date' => '2026-02-06',
                'anniversary_number' => 1,
                'users_id' => 234,
            ],
            /// Periodo viejo
            (object)[
                'period' => 1,
                'days_availables' => 2.79,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-03',
                'date_end' => '2025-07-03',
                'cutoff_date' => '2026-07-03',
                'anniversary_number' => 1,
                'users_id' => 271,
            ],
            /// Periodo viejo
            (object)[
                'period' => 1,
                'days_availables' => 6.95,
                'dv' => 1,
                'days_enjoyed' => 6,
                'date_start' => '2024-02-27',
                'date_end' => '2025-02-27',
                'cutoff_date' => '2026-02-27',
                'anniversary_number' => 1,
                'users_id' => 243,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2022-09-28',
                'date_end' => '2023-09-28',
                'cutoff_date' => '2024-09-28',
                'anniversary_number' => 1,
                'users_id' => 158,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.96,
                'dv' => 7,
                'days_enjoyed' => 7,
                'date_start' => '2023-09-28',
                'date_end' => '2024-09-28',
                'cutoff_date' => '2025-09-28',
                'anniversary_number' => 2,
                'users_id' => 158,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.85,
                'dv' => 11,
                'days_enjoyed' => 0,
                'date_start' => '2023-11-01',
                'date_end' => '2024-11-01',
                'cutoff_date' => '2025-11-01',
                'anniversary_number' => 1,
                'users_id' => 220,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 3,
                'days_enjoyed' => 9,
                'date_start' => '2023-07-06',
                'date_end' => '2024-07-06',
                'cutoff_date' => '2025-07-06',
                'anniversary_number' => 1,
                'users_id' => 201,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.14,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-06',
                'date_end' => '2025-07-06',
                'cutoff_date' => '2026-07-06',
                'anniversary_number' => 2,
                'users_id' => 201,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 8,
                'days_enjoyed' => 14,
                'date_start' => '2023-04-20',
                'date_end' => '2024-04-20',
                'cutoff_date' => '2025-04-20',
                'anniversary_number' => 7,
                'users_id' => 76,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 9.56,
                'dv' => 10,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-20',
                'date_end' => '2025-04-20',
                'cutoff_date' => '2026-04-20',
                'anniversary_number' => 8,
                'users_id' => 76,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 5,
                'days_enjoyed' => 9,
                'date_start' => '2023-01-03',
                'date_end' => '2024-01-03',
                'cutoff_date' => '2025-01-03',
                'anniversary_number' => 2,
                'users_id' => 95,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 11.67,
                'dv' => 12,
                'days_enjoyed' => 0,
                'date_start' => '2024-01-03',
                'date_end' => '2025-01-03',
                'cutoff_date' => '2026-01-03',
                'anniversary_number' => 3,
                'users_id' => 95,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 6,
                'days_enjoyed' => 6,
                'date_start' => '2023-01-30',
                'date_end' => '2024-01-30',
                'cutoff_date' => '2025-01-30',
                'anniversary_number' => 1,
                'users_id' => 34,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 9.18,
                'dv' => 9,
                'days_enjoyed' => 0,
                'date_start' => '2024-01-30',
                'date_end' => '2025-01-30',
                'cutoff_date' => '2026-01-30',
                'anniversary_number' => 2,
                'users_id' => 34,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.46,
                'dv' => 6,
                'days_enjoyed' => 5,
                'date_start' => '2024-03-13',
                'date_end' => '2025-03-13',
                'cutoff_date' => '2026-03-13',
                'anniversary_number' => 1,
                'users_id' => 133,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 18,
                'dv' => 2,
                'days_enjoyed' => 16,
                'date_start' => '2023-01-20',
                'date_end' => '2024-01-20',
                'cutoff_date' => '2025-01-20',
                'anniversary_number' => 4,
                'users_id' => 15,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.66,
                'dv' => 14,
                'days_enjoyed' => 0,
                'date_start' => '2024-01-20',
                'date_end' => '2025-01-20',
                'cutoff_date' => '2026-01-20',
                'anniversary_number' => 5,
                'users_id' => 15,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.54,
                'dv' => 4,
                'days_enjoyed' => 0,
                'date_start' => '2024-06-10',
                'date_end' => '2025-06-10',
                'cutoff_date' => '2026-06-10',
                'anniversary_number' => 1,
                'users_id' => 261,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.64,
                'dv' => 8,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-06',
                'date_end' => '2025-02-06',
                'cutoff_date' => '2026-02-06',
                'anniversary_number' => 1,
                'users_id' => 235,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 20,
                'dv' => 0,
                'days_enjoyed' => 20,
                'date_start' => '2022-10-17',
                'date_end' => '2023-10-17',
                'cutoff_date' => '2024-10-17',
                'anniversary_number' => 5,
                'users_id' => 36,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 20.79,
                'dv' => 21,
                'days_enjoyed' => 0,
                'date_start' => '2023-10-17',
                'date_end' => '2024-10-17',
                'cutoff_date' => '2025-10-17',
                'anniversary_number' => 6,
                'users_id' => 36,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 1,
                'days_enjoyed' => 15,
                'date_start' => '2022-10-14',
                'date_end' => '2023-10-14',
                'cutoff_date' => '2024-10-14',
                'anniversary_number' => 3,
                'users_id' => 48,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 17.16,
                'dv' => 17,
                'days_enjoyed' => 0,
                'date_start' => '2023-10-14',
                'date_end' => '2024-10-14',
                'cutoff_date' => '2025-10-14',
                'anniversary_number' => 4,
                'users_id' => 48,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2023-02-07',
                'date_end' => '2024-02-07',
                'cutoff_date' => '2025-02-07',
                'anniversary_number' => 1,
                'users_id' => 163,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 1,
                'days_enjoyed' => 21,
                'date_start' => '2023-09-04',
                'date_end' => '2024-09-04',
                'cutoff_date' => '2025-09-04',
                'anniversary_number' => 7,
                'users_id' => 50,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 1.32,
                'dv' => 1,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-04',
                'date_end' => '2025-09-04',
                'cutoff_date' => '2026-09-04',
                'anniversary_number' => 8,
                'users_id' => 50,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 12,
                'days_enjoyed' => 4,
                'date_start' => '2023-06-24',
                'date_end' => '2024-06-24',
                'cutoff_date' => '2025-06-24',
                'anniversary_number' => 3,
                'users_id' => 66,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 4.62,
                'dv' => 5,
                'days_enjoyed' => 0,
                'date_start' => '2024-06-24',
                'date_end' => '2025-06-24',
                'cutoff_date' => '2026-06-24',
                'anniversary_number' => 4,
                'users_id' => 66,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 9,
                'days_enjoyed' => 13,
                'date_start' => '2023-09-25',
                'date_end' => '2024-09-25',
                'cutoff_date' => '2025-09-25',
                'anniversary_number' => 7,
                'users_id' => 86,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.06,
                'dv' => 0,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-25',
                'date_end' => '2025-09-25',
                'cutoff_date' => '2026-09-25',
                'anniversary_number' => 8,
                'users_id' => 86,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.92,
                'dv' => 11,
                'days_enjoyed' => 0,
                'date_start' => '2023-10-30',
                'date_end' => '2024-10-30',
                'cutoff_date' => '2025-10-30',
                'anniversary_number' => 1,
                'users_id' => 219,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.95,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-27',
                'date_end' => '2025-02-27',
                'cutoff_date' => '2026-02-27',
                'anniversary_number' => 1,
                'users_id' => 244,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 9,
                'days_enjoyed' => 7,
                'date_start' => '2023-04-19',
                'date_end' => '2024-04-19',
                'cutoff_date' => '2025-04-19',
                'anniversary_number' => 3,
                'users_id' => 38,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.87,
                'dv' => 8,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-19',
                'date_end' => '2025-04-19',
                'cutoff_date' => '2026-04-19',
                'anniversary_number' => 4,
                'users_id' => 38,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2023-01-18',
                'date_end' => '2024-01-18',
                'cutoff_date' => '2025-01-18',
                'anniversary_number' => 8,
                'users_id' => 6,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 15.15,
                'dv' => 10,
                'days_enjoyed' => 5,
                'date_start' => '2024-01-18',
                'date_end' => '2025-01-18',
                'cutoff_date' => '2026-01-18',
                'anniversary_number' => 9,
                'users_id' => 6,
            ],
            ////DUDA, YA QUE NO SE SI ES CORRECTO EL PERIODO
            (object)[
                'period' => 2,
                'days_availables' => 18,
                'dv' => 0,
                'days_enjoyed' => 18,
                'date_start' => '2022-10-03',
                'date_end' => '2023-10-03',
                'cutoff_date' => '2024-10-03',
                'anniversary_number' => 4,
                'users_id' => 39,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 19.67,
                'dv' => 7,
                'days_enjoyed' => 13,
                'date_start' => '2023-10-03',
                'date_end' => '2024-10-03',
                'cutoff_date' => '2025-10-03',
                'anniversary_number' => 5,
                'users_id' => 39,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.98,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-26',
                'date_end' => '2025-02-26',
                'cutoff_date' => '2026-02-26',
                'anniversary_number' => 1,
                'users_id' => 241,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 0,
                'days_enjoyed' => 14,
                'date_start' => '2022-11-22',
                'date_end' => '2023-11-22',
                'cutoff_date' => '2024-11-22',
                'anniversary_number' => 2,
                'users_id' => 97,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.55,
                'dv' => 10,
                'days_enjoyed' => 4,
                'date_start' => '2023-11-22',
                'date_end' => '2024-11-22',
                'cutoff_date' => '2025-11-22',
                'anniversary_number' => 3,
                'users_id' => 97,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.80,
                'dv' => 4,
                'days_enjoyed' => 4,
                'date_start' => '2024-02-01',
                'date_end' => '2025-02-01',
                'cutoff_date' => '2026-02-01',
                'anniversary_number' => 1,
                'users_id' => 231,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 9,
                'days_enjoyed' => 7,
                'date_start' => '2023-08-04',
                'date_end' => '2024-08-04',
                'cutoff_date' => '2025-08-04',
                'anniversary_number' => 3,
                'users_id' => 9,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.61,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-08-04',
                'date_end' => '2025-08-04',
                'cutoff_date' => '2026-08-04',
                'anniversary_number' => 4,
                'users_id' => 9,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2023-03-21',
                'date_end' => '2024-03-21',
                'cutoff_date' => '2025-03-21',
                'anniversary_number' => 1,
                'users_id' => 182,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.23,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-21',
                'date_end' => '2025-03-21',
                'cutoff_date' => '2026-03-21',
                'anniversary_number' => 2,
                'users_id' => 182,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.15,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-21',
                'date_end' => '2025-02-21',
                'cutoff_date' => '2026-02-21',
                'anniversary_number' => 1,
                'users_id' => 242,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 0,
                'days_enjoyed' => 14,
                'date_start' => '2023-07-04',
                'date_end' => '2024-07-04',
                'cutoff_date' => '2025-07-04',
                'anniversary_number' => 2,
                'users_id' => 134,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.67,
                'dv' => 2,
                'days_enjoyed' => 2,
                'date_start' => '2024-07-04',
                'date_end' => '2025-07-04',
                'cutoff_date' => '2026-07-04',
                'anniversary_number' => 3,
                'users_id' => 134,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2022-10-23',
                'date_end' => '2023-10-23',
                'cutoff_date' => '2024-10-23',
                'anniversary_number' => 6,
                'users_id' => 11,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 20.43,
                'dv' => 17,
                'days_enjoyed' => 3,
                'date_start' => '2023-10-23',
                'date_end' => '2024-10-23',
                'cutoff_date' => '2025-10-23',
                'anniversary_number' => 7,
                'users_id' => 11,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 16,
                'days_enjoyed' => 0,
                'date_start' => '2023-09-17',
                'date_end' => '2024-09-17',
                'cutoff_date' => '2025-09-17',
                'anniversary_number' => 3,
                'users_id' => 91,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.44,
                'dv' => 0,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-17',
                'date_end' => '2025-09-17',
                'cutoff_date' => '2026-09-17',
                'anniversary_number' => 4,
                'users_id' => 91,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 24,
                'dv' => 9,
                'days_enjoyed' => 15,
                'date_start' => '2023-03-18',
                'date_end' => '2024-03-18',
                'cutoff_date' => '2025-03-18',
                'anniversary_number' => 15,
                'users_id' => 10,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.64,
                'dv' => 14,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-18',
                'date_end' => '2025-03-18',
                'cutoff_date' => '2026-03-18',
                'anniversary_number' => 16,
                'users_id' => 10,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 8,
                'days_enjoyed' => 6,
                'date_start' => '2023-07-14',
                'date_end' => '2024-07-14',
                'cutoff_date' => '2025-07-14',
                'anniversary_number' => 2,
                'users_id' => 137,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.23,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-14',
                'date_end' => '2025-07-14',
                'cutoff_date' => '2026-07-14',
                'anniversary_number' => 3,
                'users_id' => 137,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 24,
                'dv' => 0,
                'days_enjoyed' => 24,
                'date_start' => '2023-03-15',
                'date_end' => '2024-03-15',
                'cutoff_date' => '2025-03-15',
                'anniversary_number' => 15,
                'users_id' => 87,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.85,
                'dv' => 14,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-15',
                'date_end' => '2025-03-15',
                'cutoff_date' => '2026-03-15',
                'anniversary_number' => 16,
                'users_id' => 87,
            ],
            ////COMENZAMOS A TRABAJAR CON PROMO LIFE/////
            (object)[
                'period' => 1,
                'days_availables' => 5.15,
                'dv' => 5,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-22',
                'date_end' => '2025-04-22',
                'cutoff_date' => '2026-04-22',
                'anniversary_number' => 1,
                'users_id' => 258,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.23,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-20',
                'date_end' => '2025-03-20',
                'cutoff_date' => '2026-03-20',
                'anniversary_number' => 1,
                'users_id' => 251,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.20,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-21',
                'date_end' => '2025-03-21',
                'cutoff_date' => '2026-03-21',
                'anniversary_number' => 1,
                'users_id' => 132,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.38,
                'dv' => 6,
                'days_enjoyed' => 1,
                'date_start' => '2024-02-14',
                'date_end' => '2025-02-14',
                'cutoff_date' => '2026-02-14',
                'anniversary_number' => 1,
                'users_id' => 236,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 7,
                'days_enjoyed' => 7,
                'date_start' => '2023-06-27',
                'date_end' => '2024-06-27',
                'cutoff_date' => '2025-06-27',
                'anniversary_number' => 2,
                'users_id' => 181,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.98,
                'dv' => 4,
                'days_enjoyed' => 0,
                'date_start' => '2024-06-27',
                'date_end' => '2025-06-27',
                'cutoff_date' => '2026-06-27',
                'anniversary_number' => 3,
                'users_id' => 181,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 3,
                'days_enjoyed' => 9,
                'date_start' => '2023-03-23',
                'date_end' => '2024-03-23',
                'cutoff_date' => '2025-03-23',
                'anniversary_number' => 1,
                'users_id' => 202,
            ],

            (object)[
                'period' => 1,
                'days_availables' => 7.15,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-23',
                'date_end' => '2025-03-23',
                'cutoff_date' => '2026-03-23',
                'anniversary_number' => 2,
                'users_id' => 202,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2023-02-10',
                'date_end' => '2024-02-10',
                'cutoff_date' => '2025-02-10',
                'anniversary_number' => 8,
                'users_id' => 19,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.77,
                'dv' => 14,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-10',
                'date_end' => '2025-02-10',
                'cutoff_date' => '2026-02-10',
                'anniversary_number' => 9,
                'users_id' => 19,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.49,
                'dv' => 5,
                'days_enjoyed' => 1,
                'date_start' => '2024-03-12',
                'date_end' => '2025-03-12',
                'cutoff_date' => '2026-03-12',
                'anniversary_number' => 1,
                'users_id' => 249,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 5.15,
                'dv' => 5,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-22',
                'date_end' => '2025-04-22',
                'cutoff_date' => '2026-04-22',
                'anniversary_number' => 1,
                'users_id' => 257,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 2,
                'days_enjoyed' => 10,
                'date_start' => '2023-03-29',
                'date_end' => '2024-03-29',
                'cutoff_date' => '2025-03-29',
                'anniversary_number' => 1,
                'users_id' => 184,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.92,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-29',
                'date_end' => '2025-03-29',
                'cutoff_date' => '2026-03-29',
                'anniversary_number' => 2,
                'users_id' => 184,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 2,
                'days_enjoyed' => 10,
                'date_start' => '2023-03-29',
                'date_end' => '2024-03-29',
                'cutoff_date' => '2025-03-29',
                'anniversary_number' => 1,
                'users_id' => 185,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.92,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-29',
                'date_end' => '2025-03-29',
                'cutoff_date' => '2026-03-29',
                'anniversary_number' => 2,
                'users_id' => 185,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2022-12-04',
                'date_end' => '2023-12-04',
                'cutoff_date' => '2024-12-04',
                'anniversary_number' => 8,
                'users_id' => 102,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 17.90,
                'dv' => 13,
                'days_enjoyed' => 5,
                'date_start' => '2023-12-04',
                'date_end' => '2024-12-04',
                'cutoff_date' => '2025-12-04',
                'anniversary_number' => 9,
                'users_id' => 102,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.85,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-01',
                'date_end' => '2025-07-01',
                'cutoff_date' => '2026-07-01',
                'anniversary_number' => 1,
                'users_id' => 270,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.44,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-12',
                'date_end' => '2025-02-12',
                'cutoff_date' => '2026-02-12',
                'anniversary_number' => 1,
                'users_id' => 155,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.64,
                'dv' => 8,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-06',
                'date_end' => '2025-02-06',
                'cutoff_date' => '2026-02-06',
                'anniversary_number' => 1,
                'users_id' => 149,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 11,
                'days_enjoyed' => 3,
                'date_start' => '2023-07-11',
                'date_end' => '2024-07-11',
                'cutoff_date' => '2025-07-11',
                'anniversary_number' => 2,
                'users_id' => 139,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.37,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-11',
                'date_end' => '2025-07-11',
                'cutoff_date' => '2026-07-11',
                'anniversary_number' => 3,
                'users_id' => 139,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 18,
                'dv' => 13,
                'days_enjoyed' => 5,
                'date_start' => '2023-09-01',
                'date_end' => '2024-09-01',
                'cutoff_date' => '2025-09-01',
                'anniversary_number' => 4,
                'users_id' => 58,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 1.37,
                'dv' => 1,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-01',
                'date_end' => '2025-09-01',
                'cutoff_date' => '2026-09-01',
                'anniversary_number' => 5,
                'users_id' => 58,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.75,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-04',
                'date_end' => '2025-03-04',
                'cutoff_date' => '2026-03-04',
                'anniversary_number' => 1,
                'users_id' => 246,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 5,
                'days_enjoyed' => 7,
                'date_start' => '2023-02-21',
                'date_end' => '2024-02-21',
                'cutoff_date' => '2025-02-21',
                'anniversary_number' => 1,
                'users_id' => 73,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.34,
                'dv' => 8,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-21',
                'date_end' => '2025-02-21',
                'cutoff_date' => '2026-02-21',
                'anniversary_number' => 2,
                'users_id' => 73,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.13,
                'dv' => 8,
                'days_enjoyed' => 0,
                'date_start' => '2024-01-22',
                'date_end' => '2025-01-22',
                'cutoff_date' => '2026-01-22',
                'anniversary_number' => 1,
                'users_id' => 229,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.39,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-15',
                'date_end' => '2025-03-15',
                'cutoff_date' => '2026-03-15',
                'anniversary_number' => 1,
                'users_id' => 226,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 4,
                'days_enjoyed' => 8,
                'date_start' => '2023-02-08',
                'date_end' => '2024-02-08',
                'cutoff_date' => '2025-02-08',
                'anniversary_number' => 1,
                'users_id' => 172,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.94,
                'dv' => 9,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-08',
                'date_end' => '2025-02-08',
                'cutoff_date' => '2026-02-08',
                'anniversary_number' => 2,
                'users_id' => 172,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.79,
                'dv' => 1,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-02',
                'date_end' => '2025-09-02',
                'cutoff_date' => '2026-09-02',
                'anniversary_number' => 1,
                'users_id' => 279,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 3,
                'days_enjoyed' => 11,
                'date_start' => '2023-09-20',
                'date_end' => '2024-09-20',
                'cutoff_date' => '2025-09-20',
                'anniversary_number' => 2,
                'users_id' => 154,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.26,
                'dv' => 0,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-20',
                'date_end' => '2025-09-20',
                'cutoff_date' => '2026-09-20',
                'anniversary_number' => 3,
                'users_id' => 154,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2023-01-30',
                'date_end' => '2024-01-30',
                'cutoff_date' => '2025-01-30',
                'anniversary_number' => 1,
                'users_id' => 169,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 9.18,
                'dv' => 5,
                'days_enjoyed' => 4,
                'date_start' => '2024-01-30',
                'date_end' => '2025-01-30',
                'cutoff_date' => '2026-01-30',
                'anniversary_number' => 2,
                'users_id' => 169,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.79,
                'dv' => 1,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-02',
                'date_end' => '2025-09-02',
                'cutoff_date' => '2026-09-02',
                'anniversary_number' => 1,
                'users_id' => 277,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 9,
                'days_enjoyed' => 3,
                'date_start' => '2023-01-30',
                'date_end' => '2024-01-30',
                'cutoff_date' => '2025-01-30',
                'anniversary_number' => 1,
                'users_id' => 167,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 9.18,
                'dv' => 9,
                'days_enjoyed' => 0,
                'date_start' => '2024-01-30',
                'date_end' => '2025-01-30',
                'cutoff_date' => '2026-01-30',
                'anniversary_number' => 2,
                'users_id' => 167,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.15,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-21',
                'date_end' => '2025-02-21',
                'cutoff_date' => '2026-02-21',
                'anniversary_number' => 1,
                'users_id' => 240,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.85,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-01',
                'date_end' => '2025-07-01',
                'cutoff_date' => '2026-07-01',
                'anniversary_number' => 1,
                'users_id' => 267,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 6,
                'days_enjoyed' => 16,
                'date_start' => '2023-04-04',
                'date_end' => '2024-04-04',
                'cutoff_date' => '2025-04-04',
                'anniversary_number' => 7,
                'users_id' => 65,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.52,
                'dv' => 11,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-04',
                'date_end' => '2025-04-04',
                'cutoff_date' => '2026-04-04',
                'anniversary_number' => 8,
                'users_id' => 65,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.13,
                'dv' => 5,
                'days_enjoyed' => 3,
                'date_start' => '2024-01-22',
                'date_end' => '2025-01-22',
                'cutoff_date' => '2026-01-22',
                'anniversary_number' => 1,
                'users_id' => 205,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 0,
                'days_enjoyed' => 14,
                'date_start' => '2023-04-04',
                'date_end' => '2024-04-04',
                'cutoff_date' => '2025-04-04',
                'anniversary_number' => 2,
                'users_id' => 118,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.65,
                'dv' => 5,
                'days_enjoyed' => 3,
                'date_start' => '2024-04-04',
                'date_end' => '2025-04-04',
                'cutoff_date' => '2026-04-04',
                'anniversary_number' => 3,
                'users_id' => 118,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 20,
                'dv' => 1,
                'days_enjoyed' => 19,
                'date_start' => '2023-01-24',
                'date_end' => '2024-01-24',
                'cutoff_date' => '2025-01-24',
                'anniversary_number' => 5,
                'users_id' => 16,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 14.79,
                'dv' => 15,
                'days_enjoyed' => 0,
                'date_start' => '2024-01-24',
                'date_end' => '2025-01-24',
                'cutoff_date' => '2026-01-24',
                'anniversary_number' => 6,
                'users_id' => 16,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 20,
                'dv' => 14,
                'days_enjoyed' => 6,
                'date_start' => '2023-02-18',
                'date_end' => '2024-02-18',
                'cutoff_date' => '2025-02-18',
                'anniversary_number' => 5,
                'users_id' => 57,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.28,
                'dv' => 13,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-18',
                'date_end' => '2025-02-18',
                'cutoff_date' => '2026-02-18',
                'anniversary_number' => 6,
                'users_id' => 57,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 2,
                'days_enjoyed' => 10,
                'date_start' => '2023-02-08',
                'date_end' => '2024-02-08',
                'cutoff_date' => '2025-02-08',
                'anniversary_number' => 1,
                'users_id' => 72,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.84,
                'dv' => 9,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-08',
                'date_end' => '2025-02-08',
                'cutoff_date' => '2026-02-08',
                'anniversary_number' => 2,
                'users_id' => 72,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.59,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-09',
                'date_end' => '2025-07-09',
                'cutoff_date' => '2026-07-09',
                'anniversary_number' => 1,
                'users_id' => 275,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 17,
                'days_enjoyed' => 5,
                'date_start' => '2023-09-14',
                'date_end' => '2024-09-14',
                'cutoff_date' => '2025-09-14',
                'anniversary_number' => 9,
                'users_id' => 59,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.72,
                'dv' => 1,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-14',
                'date_end' => '2025-09-14',
                'cutoff_date' => '2026-09-14',
                'anniversary_number' => 10,
                'users_id' => 59,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 0,
                'days_enjoyed' => 14,
                'date_start' => '2022-11-16',
                'date_end' => '2023-11-16',
                'cutoff_date' => '2024-11-16',
                'anniversary_number' => 2,
                'users_id' => 96,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 13.81,
                'dv' => 13,
                'days_enjoyed' => 1,
                'date_start' => '2023-11-16',
                'date_end' => '2024-11-16',
                'cutoff_date' => '2025-11-16',
                'anniversary_number' => 3,
                'users_id' => 96,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 7.64,
                'dv' => 8,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-06',
                'date_end' => '2025-02-06',
                'cutoff_date' => '2026-02-06',
                'anniversary_number' => 1,
                'users_id' => 159,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.85,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-01',
                'date_end' => '2025-07-01',
                'cutoff_date' => '2026-07-01',
                'anniversary_number' => 1,
                'users_id' => 266,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 11.15,
                'dv' => 8,
                'days_enjoyed' => 3,
                'date_start' => '2023-10-23',
                'date_end' => '2024-10-23',
                'cutoff_date' => '2025-10-23',
                'anniversary_number' => 1,
                'users_id' => 218,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 7,
                'days_enjoyed' => 15,
                'date_start' => '2023-08-17',
                'date_end' => '2024-08-17',
                'cutoff_date' => '2025-08-17',
                'anniversary_number' => 9,
                'users_id' => 60,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.40,
                'dv' => 2,
                'days_enjoyed' => 0,
                'date_start' => '2024-08-17',
                'date_end' => '2025-08-17',
                'cutoff_date' => '2026-08-17',
                'anniversary_number' => 10,
                'users_id' => 60,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 22,
                'days_enjoyed' => 0,
                'date_start' => '2023-09-23',
                'date_end' => '2024-09-23',
                'cutoff_date' => '2025-09-23',
                'anniversary_number' => 8,
                'users_id' => 103,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 0.18,
                'dv' => 0,
                'days_enjoyed' => 0,
                'date_start' => '2024-09-23',
                'date_end' => '2025-09-23',
                'cutoff_date' => '2026-09-23',
                'anniversary_number' => 9,
                'users_id' => 103,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.59,
                'dv' => 7,
                'days_enjoyed' => 2,
                'date_start' => '2024-01-08',
                'date_end' => '2025-01-08',
                'cutoff_date' => '2026-01-08',
                'anniversary_number' => 1,
                'users_id' => 209,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.39,
                'dv' => 2,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-15',
                'date_end' => '2025-07-15',
                'cutoff_date' => '2026-07-15',
                'anniversary_number' => 1,
                'users_id' => 272,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.31,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-06-17',
                'date_end' => '2025-06-17',
                'cutoff_date' => '2026-06-17',
                'anniversary_number' => 1,
                'users_id' => 262,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 18,
                'days_enjoyed' => 4,
                'date_start' => '2023-04-16',
                'date_end' => '2024-04-16',
                'cutoff_date' => '2025-04-16',
                'anniversary_number' => 6,
                'users_id' => 79,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 9.80,
                'dv' => 10,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-16',
                'date_end' => '2025-04-16',
                'cutoff_date' => '2026-04-16',
                'anniversary_number' => 7,
                'users_id' => 79,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 4,
                'days_enjoyed' => 10,
                'date_start' => '2023-05-02',
                'date_end' => '2024-05-02',
                'cutoff_date' => '2025-05-02',
                'anniversary_number' => 2,
                'users_id' => 127,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.43,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-05-02',
                'date_end' => '2025-05-02',
                'cutoff_date' => '2026-05-02',
                'anniversary_number' => 3,
                'users_id' => 127,
            ], 
            (object)[
                'period' => 1,
                'days_availables' => 1.93,
                'dv' => 2,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-29',
                'date_end' => '2025-07-29',
                'cutoff_date' => '2026-07-29',
                'anniversary_number' => 1,
                'users_id' => 273,
            ],  
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 3,
                'days_enjoyed' => 19,
                'date_start' => '2023-04-06',
                'date_end' => '2024-04-06',
                'cutoff_date' => '2025-04-06',
                'anniversary_number' => 9,
                'users_id' => 12,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.40,
                'dv' => 10,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-06',
                'date_end' => '2025-04-06',
                'cutoff_date' => '2026-04-06',
                'anniversary_number' => 10,
                'users_id' => 12,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 8,
                'days_enjoyed' => 14,
                'date_start' => '2023-06-20',
                'date_end' => '2024-06-20',
                'cutoff_date' => '2025-06-20',
                'anniversary_number' => 7,
                'users_id' => 45,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 5.89,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-06-20',
                'date_end' => '2025-06-20',
                'cutoff_date' => '2026-06-20',
                'anniversary_number' => 8,
                'users_id' => 45,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 1.70,
                'dv' => 2,
                'days_enjoyed' => 0,
                'date_start' => '2024-08-05',
                'date_end' => '2025-08-05',
                'cutoff_date' => '2026-08-05',
                'anniversary_number' => 1,
                'users_id' => 274,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 11.38,
                'dv' => 11,
                'days_enjoyed' => 0,
                'date_start' => '2023-10-16',
                'date_end' => '2024-10-16',
                'cutoff_date' => '2025-10-16',
                'anniversary_number' => 1,
                'users_id' => 217,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 5.54,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-10',
                'date_end' => '2025-04-10',
                'cutoff_date' => '2026-04-10',
                'anniversary_number' => 1,
                'users_id' => 256,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2023-05-02',
                'date_end' => '2024-05-02',
                'cutoff_date' => '2025-05-02',
                'anniversary_number' => 1,
                'users_id' => 194,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 5.62,
                'dv' => 2,
                'days_enjoyed' => 4,
                'date_start' => '2024-05-02',
                'date_end' => '2025-05-02',
                'cutoff_date' => '2026-05-02',
                'anniversary_number' => 2,
                'users_id' => 194,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 13,
                'days_enjoyed' => 1,
                'date_start' => '2023-03-07',
                'date_end' => '2024-03-07',
                'cutoff_date' => '2025-03-07',
                'anniversary_number' => 2,
                'users_id' => 124,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.87,
                'dv' => 9,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-07',
                'date_end' => '2025-03-07',
                'cutoff_date' => '2026-03-07',
                'anniversary_number' => 3,
                'users_id' => 124,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2023-04-13',
                'date_end' => '2024-04-13',
                'cutoff_date' => '2025-04-13',
                'anniversary_number' => 1,
                'users_id' => 186,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.35,
                'dv' => 5,
                'days_enjoyed' => 1,
                'date_start' => '2024-04-13',
                'date_end' => '2025-04-13',
                'cutoff_date' => '2026-04-13',
                'anniversary_number' => 2,
                'users_id' => 186,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 5.57,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-04-09',
                'date_end' => '2025-04-09',
                'cutoff_date' => '2026-04-09',
                'anniversary_number' => 1,
                'users_id' => 254,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.59,
                'dv' => 8,
                'days_enjoyed' => 1,
                'date_start' => '2024-01-18',
                'date_end' => '2025-01-18',
                'cutoff_date' => '2026-01-18',
                'anniversary_number' => 1,
                'users_id' => 227,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 20,
                'dv' => 8,
                'days_enjoyed' => 12,
                'date_start' => '2023-03-01',
                'date_end' => '2024-03-01',
                'cutoff_date' => '2025-03-01',
                'anniversary_number' => 5,
                'users_id' => 125,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 12.56,
                'dv' => 13,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-01',
                'date_end' => '2025-03-01',
                'cutoff_date' => '2026-03-01',
                'anniversary_number' => 6,
                'users_id' => 125,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 5,
                'days_enjoyed' => 17,
                'date_start' => '2022-11-25',
                'date_end' => '2023-11-25',
                'cutoff_date' => '2024-11-25',
                'anniversary_number' => 8,
                'users_id' => 111,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 18.44,
                'dv' => 18,
                'days_enjoyed' => 0,
                'date_start' => '2023-11-25',
                'date_end' => '2024-11-25',
                'cutoff_date' => '2025-11-25',
                'anniversary_number' => 9,
                'users_id' => 111,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2022-11-05',
                'date_end' => '2023-11-05',
                'cutoff_date' => '2024-11-05',
                'anniversary_number' => 8,
                'users_id' => 108,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 19.65,
                'dv' => 3,
                'days_enjoyed' => 17,
                'date_start' => '2023-11-05',
                'date_end' => '2024-11-05',
                'cutoff_date' => '2025-11-05',
                'anniversary_number' => 9,
                'users_id' => 108,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2022-11-03',
                'date_end' => '2023-11-03',
                'cutoff_date' => '2024-11-03',
                'anniversary_number' => 9,
                'users_id' => 18,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 19.77,
                'dv' => 16,
                'days_enjoyed' => 4,
                'date_start' => '2023-11-03',
                'date_end' => '2024-11-03',
                'cutoff_date' => '2025-11-03',
                'anniversary_number' => 10,
                'users_id' => 18,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' =>  3,
                'days_enjoyed' => 11,
                'date_start' => '2022-10-18',
                'date_end' => '2023-10-18',
                'cutoff_date' => '2024-10-18',
                'anniversary_number' => 2,
                'users_id' => 107,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 15.08,
                'dv' => 15,
                'days_enjoyed' => 0,
                'date_start' => '2023-10-18',
                'date_end' => '2024-10-18',
                'cutoff_date' => '2025-10-18',
                'anniversary_number' => 3,
                'users_id' => 107,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 7,
                'days_enjoyed' => 7,
                'date_start' => '2023-08-22',
                'date_end' => '2024-08-22',
                'cutoff_date' => '2025-08-22',
                'anniversary_number' => 2,
                'users_id' => 144,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 1.53,
                'dv' => 2,
                'days_enjoyed' => 0,
                'date_start' => '2024-08-22',
                'date_end' => '2025-08-22',
                'cutoff_date' => '2026-08-22',
                'anniversary_number' => 3,
                'users_id' => 144,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.26,
                'dv' => 6,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-19',
                'date_end' => '2025-03-19',
                'cutoff_date' => '2026-03-19',
                'anniversary_number' => 1,
                'users_id' => 213,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2022-11-16',
                'date_end' => '2023-11-16',
                'cutoff_date' => '2024-11-16',
                'anniversary_number' => 7,
                'users_id' => 88,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 18.99,
                'dv' => 8,
                'days_enjoyed' => 11,
                'date_start' => '2023-11-16',
                'date_end' => '2024-11-16',
                'cutoff_date' => '2025-11-16',
                'anniversary_number' => 8,
                'users_id' => 88,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 14,
                'days_enjoyed' => 0,
                'date_start' => '2023-08-01',
                'date_end' => '2024-08-01',
                'cutoff_date' => '2025-08-01',
                'anniversary_number' => 2,
                'users_id' => 141,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 2.45,
                'dv' => 2,
                'days_enjoyed' => 0,
                'date_start' => '2024-08-01',
                'date_end' => '2025-08-01',
                'cutoff_date' => '2026-08-01',
                'anniversary_number' => 3,
                'users_id' => 141,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 18,
                'dv' => 15,
                'days_enjoyed' => 3,
                'date_start' => '2023-02-04',
                'date_end' => '2024-02-04',
                'cutoff_date' => '2025-02-04',
                'anniversary_number' => 4,
                'users_id' => 113,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 12.84,
                'dv' => 13,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-04',
                'date_end' => '2025-02-04',
                'cutoff_date' => '2026-02-04',
                'anniversary_number' => 5,
                'users_id' => 113,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 1,
                'days_enjoyed' => 13,
                'date_start' => '2023-02-01',
                'date_end' => '2024-02-01',
                'cutoff_date' => '2025-02-01',
                'anniversary_number' => 2,
                'users_id' => 126,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.40,
                'dv' => 10,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-01',
                'date_end' => '2025-02-01',
                'cutoff_date' => '2026-02-01',
                'anniversary_number' => 3,
                'users_id' => 126,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.85,
                'dv' => 6,
                'days_enjoyed' => 5,
                'date_start' => '2023-11-01',
                'date_end' => '2024-11-01',
                'cutoff_date' => '2025-11-01',
                'anniversary_number' => 1,
                'users_id' => 222,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 0,
                'days_enjoyed' => 12,
                'date_start' => '2023-05-11',
                'date_end' => '2024-05-11',
                'cutoff_date' => '2025-05-11',
                'anniversary_number' => 1,
                'users_id' => 195,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 5.28,
                'dv' => 5,
                'days_enjoyed' => 0,
                'date_start' => '2024-05-11',
                'date_end' => '2025-05-11',
                'cutoff_date' => '2026-05-11',
                'anniversary_number' => 2,
                'users_id' => 195,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 4,
                'dv' => 4,
                'days_enjoyed' => 0,
                'date_start' => '2024-05-27',
                'date_end' => '2025-05-27',
                'cutoff_date' => '2026-05-27',
                'anniversary_number' => 1,
                'users_id' => 260,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 3,
                'days_enjoyed' => 19,
                'date_start' => '2023-07-06',
                'date_end' => '2024-07-06',
                'cutoff_date' => '2025-07-06',
                'anniversary_number' => 7,
                'users_id' => 47,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 4.93,
                'dv' => 5,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-06',
                'date_end' => '2025-07-06',
                'cutoff_date' => '2026-07-06',
                'anniversary_number' => 8,
                'users_id' => 47,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 5,
                'days_enjoyed' => 17,
                'date_start' => '2023-06-04',
                'date_end' => '2024-06-04',
                'cutoff_date' => '2025-06-04',
                'anniversary_number' => 6,
                'users_id' => 112,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.85,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-06-04',
                'date_end' => '2025-06-04',
                'cutoff_date' => '2026-06-04',
                'anniversary_number' => 7,
                'users_id' => 112,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 22,
                'dv' => 0,
                'days_enjoyed' => 22,
                'date_start' => '2023-04-01',
                'date_end' => '2024-04-01',
                'cutoff_date' => '2025-04-01',
                'anniversary_number' => 9,
                'users_id' => 80,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.70,
                'dv' => 10,
                'days_enjoyed' => 1,
                'date_start' => '2024-04-01',
                'date_end' => '2025-04-01',
                'cutoff_date' => '2026-04-01',
                'anniversary_number' => 10,
                'users_id' => 80,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 3,
                'days_enjoyed' => 11,
                'date_start' => '2023-02-08',
                'date_end' => '2024-02-08',
                'cutoff_date' => '2025-02-08',
                'anniversary_number' => 2,
                'users_id' => 119,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 10.10,
                'dv' => 10,
                'days_enjoyed' => 0,
                'date_start' => '2024-02-08',
                'date_end' => '2025-02-08',
                'cutoff_date' => '2026-02-08',
                'anniversary_number' => 3,
                'users_id' => 119,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 4,
                'days_enjoyed' => 12,
                'date_start' => '2023-07-01',
                'date_end' => '2024-07-01',
                'cutoff_date' => '2025-07-01',
                'anniversary_number' => 3,
                'users_id' => 81,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 4.28,
                'dv' => 4,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-01',
                'date_end' => '2025-07-01',
                'cutoff_date' => '2026-07-01',
                'anniversary_number' => 4,
                'users_id' => 81,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 16,
                'dv' => 0,
                'days_enjoyed' => 16,
                'date_start' => '2022-11-02',
                'date_end' => '2023-11-02',
                'cutoff_date' => '2024-11-02',
                'anniversary_number' => 3,
                'users_id' => 31,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 16.22,
                'dv' => 11,
                'days_enjoyed' => 5,
                'date_start' => '2023-11-02',
                'date_end' => '2024-11-02',
                'cutoff_date' => '2025-11-02',
                'anniversary_number' => 4,
                'users_id' => 31,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 12,
                'dv' => 5,
                'days_enjoyed' => 7,
                'date_start' => '2023-03-29',
                'date_end' => '2024-03-29',
                'cutoff_date' => '2025-03-29',
                'anniversary_number' => 1,
                'users_id' => 189,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 6.92,
                'dv' => 7,
                'days_enjoyed' => 0,
                'date_start' => '2024-03-29',
                'date_end' => '2025-03-29',
                'cutoff_date' => '2026-03-29',
                'anniversary_number' => 2,
                'users_id' => 189,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 2,
                'days_enjoyed' => 12,
                'date_start' => '2022-10-04',
                'date_end' => '2023-10-04',
                'cutoff_date' => '2024-10-04',
                'anniversary_number' => 2,
                'users_id' => 83,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 15.69,
                'dv' => 16,
                'days_enjoyed' => 0,
                'date_start' => '2023-10-04',
                'date_end' => '2024-10-04',
                'cutoff_date' => '2025-10-04',
                'anniversary_number' => 3,
                'users_id' => 83,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 20,
                'dv' => 12,
                'days_enjoyed' => 8,
                'date_start' => '2022-11-06',
                'date_end' => '2023-11-06',
                'cutoff_date' => '2024-11-06',
                'anniversary_number' => 5,
                'users_id' => 85,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 19.59,
                'dv' => 20,
                'days_enjoyed' => 0,
                'date_start' => '2023-11-06',
                'date_end' => '2024-11-06',
                'cutoff_date' => '2025-11-06',
                'anniversary_number' => 6,
                'users_id' => 85,
            ],
            ////PROMOZALE
            (object)[
                'period' => 1,
                'days_availables' => 2.85,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-01',
                'date_end' => '2025-07-01',
                'cutoff_date' => '2026-07-01',
                'anniversary_number' => 1,
                'users_id' => 269,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 18,
                'dv' => 4,
                'days_enjoyed' => 14,
                'date_start' => '2022-11-26',
                'date_end' => '2023-11-26',
                'cutoff_date' => '2024-11-26',
                'anniversary_number' => 4,
                'users_id' => 43,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 16.71,
                'dv' => 17,
                'days_enjoyed' => 0,
                'date_start' => '2023-11-26',
                'date_end' => '2024-11-26',
                'cutoff_date' => '2025-11-26',
                'anniversary_number' => 5,
                'users_id' => 43,
            ],
            (object)[
                'period' => 2,
                'days_availables' => 14,
                'dv' => 11,
                'days_enjoyed' => 3,
                'date_start' => '2023-07-11',
                'date_end' => '2024-07-11',
                'cutoff_date' => '2025-07-11',
                'anniversary_number' => 2,
                'users_id' => 138,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 3.37,
                'dv' => 3,
                'days_enjoyed' => 0,
                'date_start' => '2024-07-11',
                'date_end' => '2025-07-11',
                'cutoff_date' => '2026-07-11',
                'anniversary_number' => 3,
                'users_id' => 138,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 8.36,
                'dv' => 6,
                'days_enjoyed' => 2,
                'date_start' => '2024-01-15',
                'date_end' => '2025-01-15',
                'cutoff_date' => '2026-01-15',
                'anniversary_number' => 1,
                'users_id' => 228,
            ],
            (object)[
                'period' => 1,
                'days_availables' => 4.82,
                'dv' => 5,
                'days_enjoyed' => 0,
                'date_start' => '2024-05-02',
                'date_end' => '2025-05-02',
                'cutoff_date' => '2026-05-02',
                'anniversary_number' => 1,
                'users_id' => 259,
            ],
        );

        foreach ($vacation as $vacaciones){
            VacationsAvailablePerUser::create([
                'period' => $vacaciones->period,
                'days_availables' => $vacaciones->days_availables,
                'dv' => $vacaciones->dv,
                'days_enjoyed' => $vacaciones->days_enjoyed,
                'date_start' => $vacaciones->date_start,
                'date_end' => $vacaciones->date_end,
                'cutoff_date' => $vacaciones->cutoff_date,
                'anniversary_number' => $vacaciones->anniversary_number,
                'waiting' => 0,
                'users_id' => $vacaciones->users_id,

            ]);
        }
    }
}
